apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lwwebflaskdeploy
  name: lwwebflaskdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lwwebflaskdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lwwebflaskdeploy
    spec:
      containers:
      - image: sachin62/lwwebflask:v13
        name: lwwebflask
        imagePullPolicy: Always
        resources: {}
status: {}
